name: All Products to Production

on:
  workflow_dispatch:
jobs:
  dispatch:
    strategy:
      matrix:
        product:
          - home
          - viewer
          - conversion
          - annotation
          - classification
          - comparison
          - editor
          - merger
          - metadata
          - parser
          - rewriter
          - signature
          - total
          - translation
          - watermark
          - assembly
    runs-on: ubuntu-latest
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: product.hugo.yml
          inputs: '{ "environment": "production", "product": "${{ matrix.product }}" }'
