name: All Products

on:
  workflow_dispatch:
jobs:
  dispatch:
    strategy:
      matrix:
        product:
          - home
          - viewer
          - total
    runs-on: ubuntu-latest
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: product.hugo.yml
          inputs: '{ "environment": "staging", "product": "${{ matrix.product }}" }'
