name: Build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Build environment'
        type: environment
        default: staging
        required: true
      branch:
        description: 'Branch to checkout'
        type: string
        default: main
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      GROUPDOCS_CLOUD_CLIENT_ID: ${{ secrets.GROUPDOCS_CLOUD_CLIENT_ID }}
      GROUPDOCS_CLOUD_CLIENT_SECRET: ${{ secrets.GROUPDOCS_CLOUD_CLIENT_SECRET }}
      GPT_DATA_FETCH_BASEURL: ${{ secrets.GPT_DATA_FETCH_BASEURL }}
      NEXT_TELEMETRY_DISABLED: 1
      NODE_OPTIONS: --max-old-space-size=5947

    steps:
      - uses: actions/checkout@v4
        with:
          repository: groupdocs-cloud/products2
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.REPO_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
      - run: npm run build

      - name: Upload _next directory
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          SOURCE_DIR: out/_next
          DEST_DIR: _next

      - name: Upload English pages
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --dryrun
        env:
          SOURCE_DIR: out/en

      - name: Upload everything else
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --exclude 'en/*' --exclude '404/*' --exclude '404.*' --dryrun
        env:
          SOURCE_DIR: out
