name: Build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Build environment'
        type: environment
        default: staging
        required: true
      branch:
        description: 'Branch to checkout'
        type: string
        default: main
        required: true

jobs:
  build:
    runs-on: macos-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      GROUPDOCS_CLOUD_CLIENT_ID: ${{ secrets.GROUPDOCS_CLOUD_CLIENT_ID }}
      GROUPDOCS_CLOUD_CLIENT_SECRET: ${{ secrets.GROUPDOCS_CLOUD_CLIENT_SECRET }}
      GPT_DATA_FETCH_BASEURL: ${{ secrets.GPT_DATA_FETCH_BASEURL }}
      NEXT_TELEMETRY_DISABLED: 1

    steps:
      - uses: actions/checkout@v4
        with:
          repository: groupdocs-cloud/products2
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.REPO_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
      - run: npm build

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --dryrun
        env:
          SOURCE_DIR: out/en

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --exclude 'out/en' --exclude 'out/404*' --dryrun
        env:
          SOURCE_DIR: out
