name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Build environment'
        type: environment
        default: staging
        required: true
      branch:
        description: 'Branch to checkout'
        type: string
        default: main
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GROUPDOCS_CLOUD_CLIENT_ID: ${{ secrets.GROUPDOCS_CLOUD_CLIENT_ID }}
      GROUPDOCS_CLOUD_CLIENT_SECRET: ${{ secrets.GROUPDOCS_CLOUD_CLIENT_SECRET }}
      GPT_DATA_FETCH_BASEURL: ${{ secrets.GPT_DATA_FETCH_BASEURL }}
      NEXT_TELEMETRY_DISABLED: 1
      NODE_OPTIONS: --max-old-space-size=5555

    steps:
      - uses: actions/checkout@v4
        with:
          repository: groupdocs-cloud/products2
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.REPO_TOKEN }}

      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build

      - name: Prepare artifacts
        run: |
          tar -cZf next.tar.xz -C ${{ github.workspace }}/out ./_next
          tar -cZf en-pages.tar.xz -C ${{ github.workspace }}/out/en .
          tar -cZf de-pages.tar.xz -C ${{ github.workspace }}/out ./de
          tar -cZf el-pages.tar.xz -C ${{ github.workspace }}/out ./el

      - uses: actions/upload-artifact@v3
        with:
          path: '*.tar.xz'

  deploy-shared:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    steps:
      - uses: actions/download-artifact@v3
      - run: |
          tar xZf next.tar.xz
          find

  deploy-pages:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    strategy:
      matrix:
        archive: [en-pages, de-pages, el-pages]
    steps:
      - uses: actions/download-artifact@v3
      - run: |
          tar xZf ${{ matrix.archive }}.tar.xz
          find
