name: Hugo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Build environment'
        type: environment
        default: staging
        required: true
      branch:
        description: 'Branch to checkout'
        type: string
        default: master
        required: true
      configure_one_language:
        type: string
      configure_one_product:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      NODE_ENV: ${{ github.event.inputs.environment }}
      HUGO_ENVIRONMENT: ${{ github.event.inputs.environment }}
      CONFIGURE_ONE_LANGUAGE: ${{ github.event.inputs.configure_one_language }}
      CONFIGURE_ONE_PRODUCT: ${{ github.event.inputs.configure_one_product }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: groupdocs-cloud/products.groupdocs.cloud
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.REPO_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          extended: true

      - name: Install Node.js Dependencies
        run: npm install

      - name: Fetch external resources
        run: npm run fetch

      - name: Process pages
        run: |
          npm run pages:multilingual
          npm run pages:GroupDocs.Conversion

      - name: Build (staging)
        if: ${{ github.event.inputs.environment != 'production' }}
        run: hugo --config=config-stage.toml,config.json

      - name: Build (production)
        if: ${{ github.event.inputs.environment == 'production' }}
        run: hugo --config=config-prod.toml,config.json

      - name: Deploy (staging)
        if: ${{ github.event.inputs.environment != 'production' }}
        run: hugo deploy --config=config-stage.toml,config.json --target=Home --maxDeletes=-1

      - name: Deploy (production)
        if: ${{ github.event.inputs.environment == 'production' }}
        run: hugo deploy --config=config-prod.toml,config.json --target=Home --maxDeletes=-1
