name: Hugo (One Product)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Build environment'
        type: environment
        default: staging
        required: true
      branch:
        description: 'Branch to checkout'
        type: string
        default: master
        required: true
      product:
        description: 'Product'
        type: choice
        options:
          - home
          - viewer
          - conversion
          - annotation
          - classification
          - comparison
          - editor
          - merger
          - metadata
          - parser
          - rewriter
          - signature
          - total
          - translation
          - watermark
jobs:
  build:
    runs-on: macos-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      NODE_ENV: ${{ github.event.inputs.environment }}
      NODE_OPTIONS: --max-old-space-size=11111
      HUGO_ENVIRONMENT: ${{ github.event.inputs.environment }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      CONFIGURE_ONE_LANGUAGE: ${{ matrix.configure_one_language }}
      CONFIGURE_ONE_PRODUCT: metadata

    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        configure_one_language: [en, de, el, es, fr, id, it, ja, pt, ru, zh]

    steps:
      - uses: actions/checkout@v4
        with:
          repository: groupdocs-cloud/products.groupdocs.cloud
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.REPO_TOKEN }}
      - uses: actions/setup-node@v4
      - uses: peaceiris/actions-hugo@v2
        with:
          extended: true
      - run: npm install
      - run: npm run configure
      - run: npm run pages
      - run: hugo --environment=${{ github.event.inputs.environment }}
      #- run: npm run sitemaps
      - run: hugo deploy --environment=${{ github.event.inputs.environment }} --maxDeletes=0
